### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Yucherry07**
Added my name there <//3

### CODE REVIEW

**Comment by Yucherry07** [comment]
Thank you so much :)

**Comment by ankitmalakar7** [comment]
Welcome you so much!! :)
Just once, can you confirm please that in Hacktoberfest site it's accepted or not?

**Comment by Yucherry07** [comment]
It is showing excluded :(

**Comment by ankitmalakar7** [comment]
Yeah I received that info too from someone else. Extremely sorry for that issue. 😥

**Pull request merged**
