### PR TITLE
Added navigation bar and updated css file

### PR DESCRIPTION
**Pull request by richav193**
Please review the updated website. I have added a navigation bar and updated the CSS file according to it. Please merge it in your code.

### CODE REVIEW

**Comment by ankitmalakar7** [comment]
Not responsive. Resolve the merge conflict please.

**Comment by richav193** [comment]
I have tried to make the navigation bar responsive. Please review and merge it.

**Comment by ankitmalakar7** [comment]
image

It's overlapping the header section. I suggest not to add a navbar as of now, leave this PR... add your name first in li tag, give a PR, then work on styling for a different PR.

**Comment by AmanJain18** [comment]
Hey Man, 
My yesterday Pr got excluded from hacktoberfest.. mentioning your repo does not follow the values of the event.

**Comment by ankitmalakar7** [comment]
@AmanJain18 Sorry but idk any kind of issue happening there. A lot of people already contributed & their contributions are also accepted as they informed me.

**Pull request closed without merging**
